# Generated by Django 6.0.7 on 2026-07-16 12:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradebookItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('quiz', 'Тест'), ('manual', 'Вручную')], max_length=12)),
                ('source_id', models.UUIDField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=8)),
                ('weight', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('position', models.PositiveIntegerField(default=0)),
                ('course_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradebook_items', to='courses.courserun')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликована')], default='draft', max_length=12)),
                ('feedback', models.TextField(blank=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='learning.enrollment')),
                ('graded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('gradebook_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='grading.gradebookitem')),
            ],
            options={
                'indexes': [models.Index(fields=['gradebook_item', 'enrollment'], name='grading_gra_gradebo_a2b359_idx')],
                'constraints': [models.UniqueConstraint(fields=('gradebook_item', 'enrollment'), name='unique_grade')],
            },
        ),
    ]
