# Generated by Django 6.0.7 on 2026-07-16 12:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('invited', 'Приглашён'), ('active', 'Активен'), ('completed', 'Завершён'), ('expelled', 'Отчислен')], default='active', max_length=12)),
                ('enrollment_source', models.CharField(choices=[('manual', 'Вручную'), ('self', 'Самозапись'), ('group', 'Группа')], default='self', max_length=12)),
                ('progress_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('course_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.courserun')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('not_started', 'Не начат'), ('in_progress', 'В процессе'), ('completed', 'Завершён')], default='not_started', max_length=12)),
                ('progress_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_position', models.JSONField(blank=True, default=dict)),
                ('content_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.contentblock')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='learning.enrollment')),
            ],
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['course_run', 'status'], name='learning_en_course__2ba593_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['user', 'status'], name='learning_en_user_id_b55f06_idx'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('course_run', 'user'), name='unique_enrollment'),
        ),
        migrations.AddIndex(
            model_name='contentprogress',
            index=models.Index(fields=['enrollment', 'status'], name='learning_co_enrollm_bd509a_idx'),
        ),
        migrations.AddConstraint(
            model_name='contentprogress',
            constraint=models.UniqueConstraint(fields=('enrollment', 'content_block'), name='unique_block_progress'),
        ),
    ]
