# Generated by Codex on 2026-07-18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("courses", "0004_open_published_course_runs")]

    operations = [
        migrations.AlterField(
            model_name="courserunstaff",
            name="role",
            field=models.CharField(
                choices=[
                    ("teacher", "Преподаватель"),
                    ("curator", "Куратор"),
                    ("assistant", "Ассистент"),
                ],
                max_length=12,
            ),
        ),
    ]
