# Generated by Django 6.0.7 on 2026-08-05 18:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_courseenrollmentlink'),
        ('organizations', '0003_organizationmembership_organizatio_role_40e72c_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['status'], name='courses_cou_status_158bbf_idx'),
        ),
        migrations.AddIndex(
            model_name='courserun',
            index=models.Index(fields=['status'], name='courses_cou_status_bf33df_idx'),
        ),
    ]
