# Generated by Django 5.0 on 2026-07-27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="image",
            field=models.ImageField(blank=True, upload_to="question_images/"),
        ),
        migrations.AddField(
            model_name="questionoption",
            name="marker_x",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="questionoption",
            name="marker_y",
            field=models.FloatField(blank=True, null=True),
        ),
    ]