# Generated by Django 6.0.7 on 2026-07-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='institution_type',
            field=models.CharField(choices=[('university', 'ВУЗ'), ('college', 'Колледж')], default='university', max_length=16),
        ),
    ]
