# Generated by Django 6.0.7 on 2026-08-05 18:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_institution_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='organizationmembership',
            index=models.Index(fields=['role', 'status'], name='organizatio_role_40e72c_idx'),
        ),
    ]
